# Generated by Django 4.2.6 on 2023-11-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglink', '0002_alter_blog_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
